//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogManagementSystem.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserId { get; set; }
        public int LogId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Log Log { get; set; }
        public virtual User User { get; set; }
    }
}
